// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AnalyzeParagraph(arg1) {
  return window['go']['main']['App']['AnalyzeParagraph'](arg1);
}

export function CanIllustrate(arg1) {
  return window['go']['main']['App']['CanIllustrate'](arg1);
}

export function CompleteParagraph(arg1) {
  return window['go']['main']['App']['CompleteParagraph'](arg1);
}

export function CompleteWord(arg1, arg2) {
  return window['go']['main']['App']['CompleteWord'](arg1, arg2);
}

export function GetIllustration(arg1) {
  return window['go']['main']['App']['GetIllustration'](arg1);
}

export function HasAnyAPIKey() {
  return window['go']['main']['App']['HasAnyAPIKey']();
}

export function LoadDraft() {
  return window['go']['main']['App']['LoadDraft']();
}

export function OpenFile() {
  return window['go']['main']['App']['OpenFile']();
}

export function SaveDraft(arg1) {
  return window['go']['main']['App']['SaveDraft'](arg1);
}

export function SaveFile(arg1, arg2) {
  return window['go']['main']['App']['SaveFile'](arg1, arg2);
}

export function SaveFileAs(arg1) {
  return window['go']['main']['App']['SaveFileAs'](arg1);
}
