// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function LoadDraft() {
  return window['go']['main']['App']['LoadDraft']();
}

export function SaveDraft(arg1) {
  return window['go']['main']['App']['SaveDraft'](arg1);
}
