// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function LoadDraft():Promise<main.Draft>;

export function OpenFile():Promise<main.Draft>;

export function SaveDraft(arg1:main.Draft):Promise<void>;

export function SaveFile(arg1:string,arg2:main.Draft):Promise<void>;

export function SaveFileAs(arg1:main.Draft):Promise<string>;
