// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function HasDeepSeekAPIKey() {
  return window['go']['main']['CredentialStore']['HasDeepSeekAPIKey']();
}

export function HasUnsplashAPIKey() {
  return window['go']['main']['CredentialStore']['HasUnsplashAPIKey']();
}

export function RemoveDeepSeekAPIKey() {
  return window['go']['main']['CredentialStore']['RemoveDeepSeekAPIKey']();
}

export function RemoveUnsplashAPIKey() {
  return window['go']['main']['CredentialStore']['RemoveUnsplashAPIKey']();
}

export function SaveDeepSeekAPIKey(arg1) {
  return window['go']['main']['CredentialStore']['SaveDeepSeekAPIKey'](arg1);
}

export function SaveUnsplashAPIKey(arg1) {
  return window['go']['main']['CredentialStore']['SaveUnsplashAPIKey'](arg1);
}
