// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function HasDeepSeekAPIKey():Promise<boolean>;

export function HasUnsplashAPIKey():Promise<boolean>;

export function RemoveDeepSeekAPIKey():Promise<void>;

export function RemoveUnsplashAPIKey():Promise<void>;

export function SaveDeepSeekAPIKey(arg1:string):Promise<void>;

export function SaveUnsplashAPIKey(arg1:string):Promise<void>;
